const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      oldPrice: undefined,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 1,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      oldPrice: undefined,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: true,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      oldPrice: undefined,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: true,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'chair',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'chair',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'sofa',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: true,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'sofa',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'dining',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'table',
      oldPrice: 40,
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      comparing: false,
      isFavorite: false,
      rating: 0,
    },
  ],
  cart: {
    products: [],
  },
  brands: [
    {
      id: 'brand-1',
      name: 'brand 1',
      image: '/images/brands/brand-1.png',
    },
    {
      id: 'brand-2',
      name: 'brand 2',
      image: '/images/brands/brand-2.png',
    },
    {
      id: 'brand-3',
      name: 'brand 3',
      image: '/images/brands/brand-3.png',
    },
    {
      id: 'brand-4',
      name: 'brand 4',
      image: '/images/brands/brand-4.png',
    },
    {
      id: 'brand-5',
      name: 'brand 5',
      image: '/images/brands/brand-5.png',
    },
    {
      id: 'brand-6',
      name: 'brand 6',
      image: '/images/brands/brand-6.png',
    },
    {
      id: 'brand-7',
      name: 'brand 7',
      image: '/images/brands/brand-7.png',
    },
    {
      id: 'brand-8',
      name: 'brand 8',
      image: '/images/brands/brand-8.png',
    },
    {
      id: 'brand-9',
      name: 'brand 9',
      image: '/images/brands/brand-9.png',
    },
    {
      id: 'brand-10',
      name: 'brand 10',
      image: '/images/brands/brand-10.png',
    },
  ],
};

export default initialState;
